# hostname.yml
# The Puppet agent uses the hostname to communicate with the Puppet Server.
# So, make sure agent nodes can resolve the hostname of the Puppet Server
# with the help of /etc/hosts file
---
  - name: Puppet Hostname
    hosts: master
    vars:
      hosts_file: /etc/hosts
    tasks:
      - name: Checking for "{{ hosts_file }}"
        shell: grep -c "^puppet" "{{ hosts_file }}" || true
        register: check_grep
        changed_when: False

      - name: Add hostname
        become: True
        lineinfile:
          dest: "{{ hosts_file }}"
          line: 127.0.0.1 puppet
        when: check_grep.stdout == "0"
