# install.yml
---
  - name: Setup puppet
    hosts: master
    gather_facts: no
    become: True
    tasks:
      - name: Check if RPM package is installed
        shell: rpm -qa | grep puppet
        ignore_errors: yes
        changed_when: False
        register: rpm_check

      - name: Install RPM package
        shell: rpm -Uvh https://yum.puppet.com/puppet5-release-el-8.noarch.rpm
        ignore_errors: yes
        changed_when: False
        when: rpm_check.rc == 1

      - name: Install with yum
        yum:
          name: puppetserver
          state: present
