# install.yml
---
  - name: Setup puppet
    hosts: puppet
    tasks:
      - name: Search relevant RPM
        yum: name=https://yum.puppet.com/puppet5-release-el-7.noarch.rpm

      - name: Check puppet with yum
        yum:
          name: puppet
          state: present

      - name: Make sure a service is running
        ansible.builtin.systemd:
          name: puppetserver
          state: started

      - name: Enable service and make sure it is not masked
        ansible.builtin.systemd:
          name: puppetserver
          enabled: yes
          masked: no

      - name: Make sure firewall is running
        become: True
        service:
          name: firewalld
          state: started
          enabled: True

      - name: Permit traffic for a service
        become: True
        ansible.posix.firewalld:
          permanent: yes
          port: 8140/tcp
          state: enabled
          immediate: True
