# manifests.yml
---
  - name: Add manifests
    hosts: master
    gather_facts: no
    become: True
    vars:
      modules: /etc/puppetlabs/code/environments/production/modules/wipe/manifests
    tasks:
      - name: Add modules
        file: path={{ modules }} state=directory

      - name:
        template:
          src: templates/params.j2
          dest: "{{ modules }}/params.pp"
