# puppetserver.yml
---
  - name: Run service
    hosts: master
    gather_facts: no
    become: True
    vars:
      service_file: /etc/sysconfig/puppetserver
      conf_file: /etc/puppetlabs/puppet/puppet.conf
    tasks:
      - name: Memory allocation
        ansible.builtin.replace:
          path: "{{ service_file }}"
          regexp: 'Xms2g -Xmx2g'
          replace: 'Xms1g -Xmx1g'
        register: memory

      - name: Check autosigning
        shell: grep -c "autosign" "{{ conf_file }}" || true
        register: autosign
        changed_when: False

      - name: Enable autosigning
        lineinfile:
          path: "{{ conf_file }}"
          line: autosign = true
        when: autosign.stdout == "0"

      - name: Make sure a service is running
        service:
          name: puppetserver
          state: started
          enabled: yes
          masked: no

      - name: Restart a service
        service:
          name: puppetserver
          state: restarted
          enabled: yes
        when: (memory.changed) or (autosign.stdout == "0")
