# secure_path.yml
---
  - name: Allow sudoers run service
    hosts: master
    gather_facts: no
    vars:
      sudoers_file: /etc/sudoers
    become: True
    tasks:
      - name: Checking for "{{ sudoers_file }}"
        shell: grep -c "puppet" "{{ sudoers_file }}" || true
        register: missing
        changed_when: False

      - name: Change permissions for sudoers
        ansible.builtin.file:
          path: "{{ sudoers_file }}"
          mode: '0640'
        when: missing.stdout == "0"

      - name: Add secure_path
        lineinfile:
          path: "{{ sudoers_file }}"
          regexp: '^(.*)secure_path(.*)$'
          line: Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin
          backrefs: yes
        when: missing.stdout == "0"

      - name: Change back permissions for sudoers
        ansible.builtin.file:
          path: "{{ sudoers_file }}"
          mode: '0440'
        when: missing.stdout == "0"
